### ISSUE TITLE
[OSX Only] Error: PeerInfo not found - uncaught error after running tests

### ISSUE THREAD

**Issue by sdtsui** [dfinity/js-libp2p-gossip-discovery#5]
@wanderer continuing our work on #4 from last night, I have 
- repro instructions for the test failure
- some clues as to how to fix it -- wanted to check with you first

Recapping Current Behavior: I get the following error **after** case 5 'OK's when running tests on my machine: `OSX Sierra 10.12.6`
```
/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/peer-book/src/index.js:90
    throw new Error('PeerInfo not found')
```
Expected Behavior: tests should pass and complete running, without uncaught errors.

More detailed output: **I can repro this 10x+ with repeated runs**
```
# errors - invalid len
gossip: START
  discovery:gossip connected peer, restarting discovery +14ms
ok 5 should be equal
gossip: STOP1
Libp2p Node - node.unhandle - start
Swarm - unhandle - start
Swarm - unhandle - end
Libp2p Node - node.unhandle - end
gossip: STOP2
/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/peer-book/src/index.js:90
    throw new Error('PeerInfo not found')
    ^

Error: PeerInfo not found
    at PeerBook.get (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/peer-book/src/index.js:90:11)
    at MultiplexMuxer.muxedConn.once (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/libp2p-swarm/src/dial.js:188:29)
    at Object.onceWrapper (events.js:312:30)
    at emitNone (events.js:105:13)
    at MultiplexMuxer.emit (events.js:207:7)
    at MultiplexMuxer.multiplex.on (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/libp2p-multiplex/src/muxer.js:19:38)
    at emitNone (events.js:110:20)
    at Multiplex.emit (events.js:207:7)
    at Multiplex.destroy (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/multiplex/src/index.js:473:10)
    at /Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/pump/index.js:43:45
```

--------

Possible cause: I think discovery gets restarted as part of the test, the test passes, and one of the nodes has yet to invoke its PeerBook's `.get` --- when `stop` is called, the `unhandler` removes the Peer too early. When `.get` finally gets called, the peer isn't there, and the error is thrown.

Putting the contents of `stop` in a timeout fixes the issue, but seems a little too hacky. Wondering if you have thoughts on how to `unhandle` more smoothly.
```
    setTimeout(
      () => {
        this.node.unhandle(PROTO)
        this.node.removeListener('peer:connect', this._onConnection)
      },
      10
    )
```
(This works 10x+ as well, a timeout of `1` does not though)

--------

Possibly related note: Are we sure `removeListener` will work as expected? If I remember correctly,`removeListener` finds handlers by reference. 

We add the listener after passing it to [`bind`](https://github.com/dfinity/js-libp2p-gossip-discovery/blob/master/index.js#L59), and remove it [without `bind`](https://github.com/dfinity/js-libp2p-gossip-discovery/blob/master/index.js#L53). These will be different functions and `removeListener` might not find what it needs -- would it be better to save to a named variable?

**Comment by sdtsui** [comment]
#6  appears to fix this on OSX (20+ runs). Linux is still stable (10+ test runs on ec2.micro instance).
Will close when that PR is merged.

**Comment by sdtsui** [comment]
Documenting the errors before closing, as we wrap up #6 

Uncaught error: `pull-pair` ‘already piped’
```Sze-Hungs-Air:js-libp2p-gossip-discovery sdt$ npm run test

> libp2p-gossip-discovery@0.0.0 test /Users/sdt/dfinity/js-libp2p-gossip-discovery
> node ./tests/index.js

TAP version 13
# tests
  discovery:gossip connected peer, restarting discovery +0ms
  discovery:gossip connected peer, restarting discovery +18ms
ok 1 (unnamed assert)
  discovery:gossip connected peer, restarting discovery +13ms
ok 2 (unnamed assert)
  discovery:gossip connected peer, restarting discovery +16ms
  discovery:gossip connected peer, restarting discovery +6ms
  discovery:gossip already have peer  QmRjW5BwyujchbXbGk9baidLzdbCKG9D3MJeA8mcvaJXrC +24ms
  discovery:gossip already have peer  QmedBznidXm2GfdNMMBwPtJAJEPnwbxMqag73dNTtbhBGd +0ms
ok 3 (unnamed assert)
  discovery:gossip already have peer  QmedBznidXm2GfdNMMBwPtJAJEPnwbxMqag73dNTtbhBGd +6ms
  discovery:gossip connected peer, restarting discovery +0ms
# erros - no data sent
/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/pull-pair/index.js:11
      throw new Error('already piped')
      ^

Error: already piped
    at sink (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/pull-pair/index.js:11:13)
    at Connection.consume (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/pull-defer/sink.js:7:17)
    at pull (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/pull-stream/pull.js:43:9)
    at Dialer.handle (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/multistream-select/src/dialer/index.js:47:5)
    at protocolHandshake (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/libp2p-swarm/src/dial.js:187:10)
    at attemptMuxerUpgrade (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/libp2p-swarm/src/dial.js:61:11)
    at ms.select (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/libp2p-swarm/src/dial.js:149:15)
    at f (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/once/once.js:25:25)
    at select (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/multistream-select/src/dialer/index.js:76:16)
    at pullLP.decodeFromReader (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/multistream-select/src/select.js:20:14)
```

`PeerBook` failed get:
```> libp2p-gossip-discovery@0.0.0 test /Users/sdt/dfinity/js-libp2p-gossip-discovery
> node ./tests/index.js

TAP version 13
# tests
  discovery:gossip connected peer, restarting discovery +0ms
  discovery:gossip connected peer, restarting discovery +11ms
ok 1 (unnamed assert)
  discovery:gossip connected peer, restarting discovery +8ms
ok 2 (unnamed assert)
  discovery:gossip connected peer, restarting discovery +9ms
  discovery:gossip connected peer, restarting discovery +3ms
  discovery:gossip already have peer  QmRzsoK7zByKRAttDANraSjokKdhAknVZRjDoghoAwJNJq +11ms
  discovery:gossip already have peer  QmWUEJw6vb8RkpfznAnhSPsK5rxVYggubGwHzmfRKNpsDy +0ms
ok 3 (unnamed assert)
  discovery:gossip already have peer  QmWUEJw6vb8RkpfznAnhSPsK5rxVYggubGwHzmfRKNpsDy +5ms
  discovery:gossip connected peer, restarting discovery +0ms
# erros - no data sent
  discovery:gossip connected peer, restarting discovery +2s
  discovery:gossip connected peer, restarting discovery +14ms
  discovery:gossip connected peer, restarting discovery +4ms
ok 4 should be equal
# erros - invalid len
/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/peer-book/src/index.js:90
    throw new Error('PeerInfo not found')
    ^

Error: PeerInfo not found
    at PeerBook.get (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/peer-book/src/index.js:90:11)
    at MultiplexMuxer.muxedConn.once (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/libp2p-swarm/src/dial.js:165:29)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at MultiplexMuxer.emit (events.js:207:7)
    at MultiplexMuxer.multiplex.on (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/libp2p-multiplex/src/muxer.js:19:38)
    at emitNone (events.js:110:20)
    at Multiplex.emit (events.js:207:7)
    at Multiplex.destroy (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/multiplex/src/index.js:473:10)
    at /Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/pump/index.js:43:45
```

`libp2p` - “node is not started yet”
```Sze-Hungs-Air:js-libp2p-gossip-discovery sdt$ npm run test

> libp2p-gossip-discovery@0.0.0 test /Users/sdt/dfinity/js-libp2p-gossip-discovery
> node ./tests/index.js

TAP version 13
# tests
  discovery:gossip connected peer, restarting discovery +0ms
  discovery:gossip connected peer, restarting discovery +15ms
ok 1 (unnamed assert)
  discovery:gossip connected peer, restarting discovery +13ms
ok 2 (unnamed assert)
  discovery:gossip connected peer, restarting discovery +8ms
  discovery:gossip connected peer, restarting discovery +4ms
ok 3 (unnamed assert)
  discovery:gossip already have peer  QmP9TWCAsHLs6a3hcCbqE6WZs3VhQF6QsmkFPAFmmcuMa6 +12ms
  discovery:gossip connected peer, restarting discovery +5ms
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: The libp2p node is not started yet
    at Node.dial (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/libp2p/src/index.js:251:5)
    at newPeers.forEach.peer (/Users/sdt/dfinity/js-libp2p-gossip-discovery/index.js:79:14)
    at Array.forEach (<anonymous>)
    at handlePeers._peerDiscovery (/Users/sdt/dfinity/js-libp2p-gossip-discovery/index.js:77:16)
    at handlePeers._onConnection (/Users/sdt/dfinity/js-libp2p-gossip-discovery/index.js:70:12)
    at emitOne (events.js:115:13)
    at Node.emit (events.js:210:7)
    at Swarm.Node.swarm.on (/Users/sdt/dfinity/js-libp2p-gossip-discovery/node_modules/libp2p/src/index.js:49:14)
    at emitOne (events.js:115:13)
    at Swarm.emit (events.js:210:7)
```

These errors are :
(i) non-deterministic relative to sequence of test runs.
(ii) don’t appear to have a discernible pattern (sometimes repeat errors of the same kind occur, no discernible 'cycling' between the three errors)
all on `master:latest`  i.e. [12a9eb](https://github.com/dfinity/js-libp2p-gossip-discovery/commit/12a9eb391f80bc77b9552459b67575df8913ba45)

**Comment by sdtsui** [comment]
Fixed in the following commits:
https://github.com/dfinity/js-libp2p-gossip-discovery/commit/3b101b71a6f06d610825d5153d9f0159d292da8d

https://github.com/dfinity/js-libp2p-gossip-discovery/commit/4e71f52a2d519ed200cdb9b2788145c5005915b8

https://github.com/dfinity/js-libp2p-gossip-discovery/commit/77060773b66ca38cbbc153cddb8c24dfb7325d46

Closing, and closing related issues.
